flyway.url=jdbc:mysql://100.100.107.115:3318/reportDb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
flyway.user=BTREPORT
flyway.password=BTREPORT
flyway.locations=filesystem:src/main/resources/db/migration
